### PR TITLE
Use pyupgrade

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by basnijholt** [comment]
@jbweston

**Comment by jbweston** [comment]
LGTM, Thanks for the contrib!

**Review by jbweston — APPROVED** [review]
LGTM, Thanks for the contrib!

**Comment by jbweston** [comment]
Ok, there's some imports to be removed; also we need to update `setup.cfg` to require Python 3.9

**Comment by basnijholt** [comment]
I updated `python_requires = >=3.9`

**Pull request merged**
